version: '3'

# networks:
#   project_network:
#     driver: bridge
#     name: sdcc_project

services:
  # Servizio per il nodo IPFS
  ipfs-node:
    build: 
      context: ./ipfs-client
    container_name: ipfs-client
    # networks:
    #   - sdcc_project

  # Servizio per il nodo Substrate
  substrate-node:
    build: 
      context: ./substrate/
    container_name: substrate-node
    # networks:
    #   - sdcc_project# Monta la cartella substrate