version: '3'

networks:
  titanh_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16


services:

  # First substrate node
  titanh-substrate-1:
    image: titanh-substrate
    container_name: titanh-substrate-1
    networks:
      titanh_network:
    volumes:
      - ./scripts/substrate:/home/titanh-substrate/scripts
      - ./config/chain-specs:/home/titanh-substrate/specs
    environment:
      - CHAIN_SPEC=/home/titanh-substrate/specs/titanhSpecRaw.json
      - NODE_NAME=titanh-substrate-1
      - SEED_PHRASE=${SEED_SUBSTRATE_NODE_1}
    tty: true
    ports:
      - 9944:9944
    entrypoint: ["/home/titanh-substrate/scripts/validator-entrypoint.sh"]

  # Second substrate node
  titanh-substrate-2:
    image: titanh-substrate
    container_name: titanh-substrate-2
    networks:
      - titanh_network
    volumes:
      - ./scripts/substrate:/home/titanh-substrate/scripts
      - ./config/chain-specs:/home/titanh-substrate/specs
    environment:
      - CHAIN_SPEC=/home/titanh-substrate/specs/titanhSpecRaw.json
      - NODE_NAME=substrate-titanh-node-2
      - SEED_PHRASE=${SEED_SUBSTRATE_NODE_2}
      - BOOTNODE_HOST=titanh-substrate-1
    depends_on:
      - titanh-substrate-1
    tty: true
    entrypoint: ["/home/titanh-substrate/scripts/validator-entrypoint.sh"]

  # Ipfs instances associated to titanh-pinning- 
  titanh-ipfs-1:
    image: titanh-ipfs
    container_name: titanh-ipfs-1
    networks:
      - titanh_network
    volumes:
    - ./scripts/ipfs:/home/titanh-ipfs/config
    environment:
      - IPFS_REPLICAS=2
    
      - NODE_1_PRIVKEY=${IPFS_1_NODE_1_PRIVKEY}
      - NODE_1_PEERID=${IPFS_1_NODE_1_PEERID}

      - NODE_2_PRIVKEY=${IPFS_1_NODE_2_PRIVKEY}
      - NODE_2_PEERID=${IPFS_1_NODE_2_PEERID}
    ports:
      - 5001:5001
      - 8080:8080
    entrypoint: ["/home/titanh-ipfs/config/run-nodes.sh"]
    

  titanh-ipfs-2:
    image: titanh-ipfs
    container_name: titanh-ipfs-2
    networks:
      - titanh_network
    volumes:
    - ./scripts/ipfs:/home/titanh-ipfs/config
    environment:
      - IPFS_REPLICAS=2

      - NODE_1_PRIVKEY=${IPFS_2_NODE_1_PRIVKEY}
      - NODE_1_PEERID=${IPFS_2_NODE_1_PEERID}

      - NODE_2_PRIVKEY=${IPFS_2_NODE_2_PRIVKEY}
      - NODE_2_PEERID=${IPFS_2_NODE_2_PEERID}
    depends_on:
      - titanh-ipfs-1
    entrypoint: ["/home/titanh-ipfs/config/run-nodes.sh"]



  # pinning-node:
  #   build:
  #     context: ../pinning-node
  #     dockerfile: ../docker/dockerfiles/pinning-node.Dockerfile
  #   container_name: pinning-node
  #   networks:
  #     - titanh_network
  #   volumes:
  #     - ./config/pinning-node-1.json:/home/pinning_node/config/pinning-config.json
  #   tty: true
  #   ports:
  #     - "9944:9944"
  #     - "9615:9615"
  #     - "30333:30333"