version: '3'

networks:
  titanh_network:
    driver: bridge

services:
  # First substrate node
  # substrate-titanh-node-1:
  #   image: substrate-titanh-node
  #   container_name: substrate-titanh-node-1
  #   networks:
  #     titanh_network:
  #   volumes:
  #     - ./scripts/substrate-node:/home/titanh/scripts
  #     - ./config/chain-specs:/home/titanh/specs
  #   environment:
  #     - CHAIN_SPEC=/home/titanh/specs/titanhSpecRaw.json
  #     - NODE_NAME=substrate-titanh-node-1
  #     - SEED_PHRASE=${SEED_SUBSTRATE_NODE_1}
  #   tty: true
  #   ports:
  #     - "9944:9944"
  #   entrypoint: ["/home/titanh/scripts/validator-entrypoint.sh"]

  # Second substrate node
  # substrate-titanh-node-2:
  #   image: substrate-titanh-node
  #   container_name: substrate-titanh-node-2
  #   networks:
  #     - titanh_network
  #   volumes:
  #     - ./scripts/substrate-node:/home/titanh/scripts
  #     - ./config/chain-specs:/home/titanh/specs
  #   environment:
  #     - CHAIN_SPEC=/home/titanh/specs/titanhSpecRaw.json
  #     - NODE_NAME=substrate-titanh-node-2
  #     - SEED_PHRASE=${SEED_SUBSTRATE_NODE_2}
  #     - BOOTNODE_HOST=substrate-titanh-node-1
  #   depends_on:
  #     - substrate-titanh-node-1
  #   tty: true
  #   entrypoint: ["/home/titanh/scripts/validator-entrypoint.sh"]

  titanh-ipfs-1:
    image: titanh-ipfs
    container_name: titanh-ipfs-1
    networks:
      - titanh_network
    volumes:
    - ./config/ipfs/node-1:/home/titanh-ipfs/ipfs
    - ./scripts/ipfs:/home/titanh-ipfs/scripts

    environment:
      - IPFS_REPLICAS=2
    ports:
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
      - "4001:4001"  # Swarm
    #entrypoint: ["/home/titanh-ipfs/scripts/ipfs-init.sh"]
    command: sleep 100000000000


  titanh-ipfs-2:
    image: titanh-ipfs
    container_name: titanh-ipfs-2
    networks:
      - titanh_network
    volumes:
    -  ./scripts/ipfs:/home/titanh-ipfs/scripts
    - ./config/ipfs/node-2:/home/titanh-ipfs/ipfs
    environment:
      - IPFS_REPLICAS=2
    command: sleep 10000000000000000
    #entrypoint: ["/home/titanh-ipfs/scripts/ipfs-init.sh"]



  # pinning-node:
  #   build:
  #     context: ../pinning-node
  #     dockerfile: ../docker/dockerfiles/pinning-node.Dockerfile
  #   container_name: pinning-node
  #   networks:
  #     - titanh_network
  #   volumes:
  #     - ./config/pinning-node-1.json:/home/pinning_node/config/pinning-config.json
  #   tty: true


  #   ports:
  #     - "9944:9944"
  #     - "9615:9615"
  #     - "30333:30333"