version: '3'

networks:
  titanh_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16


services:

  # First substrate node
  titanh-substrate-1:
    image: titanh-substrate
    container_name: titanh-substrate-1
    networks:
      titanh_network:
    volumes:
      - ./scripts/substrate:/home/titanh-substrate/scripts
      - ./config/chain-specs:/home/titanh-substrate/specs
    environment:
      - CHAIN_SPEC=/home/titanh-substrate/specs/titanhSpecRaw.json
      - NODE_NAME=titanh-substrate-1
      - SEED_PHRASE=${SEED_SUBSTRATE_NODE_1}
      - BLOCK_PRUNING=3600 # Validator will discard blocks for a depth of 3600 blocks
    tty: true
    ports:
      - 9944:9944
    entrypoint: ["/home/titanh-substrate/scripts/validator-entrypoint.sh"]

  # Second substrate node
  titanh-substrate-2:
    image: titanh-substrate
    container_name: titanh-substrate-2
    networks:
      - titanh_network
    volumes:
      - ./scripts/substrate:/home/titanh-substrate/scripts
      - ./config/chain-specs:/home/titanh-substrate/specs
    environment:
      - CHAIN_SPEC=/home/titanh-substrate/specs/titanhSpecRaw.json
      - NODE_NAME=substrate-titanh-node-2
      - SEED_PHRASE=${SEED_SUBSTRATE_NODE_2}
      - BOOTNODE_HOST=titanh-substrate-1
      - BLOCK_PRUNING=3600
    depends_on:
      - titanh-substrate-1
    tty: true
    entrypoint: ["/home/titanh-substrate/scripts/validator-entrypoint.sh"]


  # Ipfs instances associated to titanh-pinning-1 
  titanh-ipfs-1:
    image: titanh-ipfs
    container_name: titanh-ipfs-1
    networks:
      - titanh_network
    volumes:
    - ./scripts/ipfs:/home/titanh-ipfs/scripts
    - ./config/ipfs/bootnodes.json:/home/titanh-ipfs/config/bootnodes.json
    - ./config/ipfs/ipfs-keys-1.json:/home/titanh-ipfs/config/ipfs-keys.json
    ports:
      - 5001:5001
      - 8080:8080
    entrypoint: ["/home/titanh-ipfs/scripts/run-nodes.sh"]
    
  # Ipfs instances associated to titanh-pinning-2
  titanh-ipfs-2:
    image: titanh-ipfs
    container_name: titanh-ipfs-2
    networks:
      - titanh_network
    volumes:
    - ./scripts/ipfs:/home/titanh-ipfs/scripts
    - ./config/ipfs/bootnodes.json:/home/titanh-ipfs/config/bootnodes.json
    - ./config/ipfs/ipfs-keys-2.json:/home/titanh-ipfs/config/ipfs-keys.json
    depends_on:
      - titanh-ipfs-1
    entrypoint: ["/home/titanh-ipfs/scripts/run-nodes.sh"]

  
  # Just for testing
  titanh-pinning-1:
    image: titanh-pinning
    container_name: titanh-pinning-1
    networks:
      - titanh_network
    volumes:
      - ../api:/home/titanh-pinning/api
      - ../cli/pinning-committee:/home/titanh-pinning/cli/pinning-committee
      - ../pinning-node:/home/titanh-pinning/pinning-node
      - ./config/pinning/node-1:/home/titanh-pinning/config
      - ./scripts/pinning:/home/titanh-pinning/scripts
    environment:
      - PINNING_INSTANCES=3
      - VALIDATOR_SEED=${SEED_SUBSTRATE_NODE_1}
      - CHAIN_RPC=ws://titanh-substrate-1:9944
      - IPFS_RPC=http://titanh-ipfs-1:5001
      - REPLICATION_FACTOR=2
      - FAILURE_RETRY=2
    tty: true
    depends_on:
      - titanh-substrate-1
      - titanh-ipfs-1
    command: sleep 10000000000000000000000000000000000


  titanh-pinning-2:
    image: titanh-pinning
    container_name: titanh-pinning-2
    networks:
      - titanh_network
    volumes:
      - ../api:/home/titanh-pinning/api
      - ../cli/pinning-committee:/home/titanh-pinning/cli/pinning-committee
      - ../pinning-node:/home/titanh-pinning/pinning-node
      - ./config/pinning/node-2:/home/titanh-pinning/config
      - ./scripts/pinning:/home/titanh-pinning/scripts
    environment:
      - PINNING_INSTANCES=3
      - VALIDATOR_SEED=${SEED_SUBSTRATE_NODE_2}
      - CHAIN_RPC=ws://titanh-substrate-2:9944
      - IPFS_RPC=http://titanh-ipfs-2:5001
      - REPLICATION_FACTOR=2
      - FAILURE_RETRY=2
    tty: true
    depends_on:
      - titanh-substrate-2
      - titanh-ipfs-2
    command: sleep 10000000000000000000000000000000000
  

  # titanh-pinning-1:
  #   image: titanh-pinning
  #   container_name: titanh-pinning-1
  #   networks:
  #     - titanh_network
  #   volumes:
  #     - ./config/pinning/node-1:/home/titanh-pinning/config
  #     - ./scripts/pinning/run-nodes.sh:/home/titanh-pinning/scripts/run-nodes.sh
  #   environment:
  #     - PINNING_INSTANCES=3
  #     - VALIDATOR_SEED=${SEED_SUBSTRATE_NODE_1}
  #     - CHAIN_RPC=ws://titanh-substrate-1:9944
  #     - FAILURE_RETRY=2
  #   tty: true
  #   depends_on:
  #     - titanh-substrate-1
  #     - titanh-ipfs-1
  #   entrypoint: ["/home/titanh-pinning/scripts/run-nodes.sh"]
  

  # titanh-pinning-2:
  #   image: titanh-pinning
  #   container_name: titanh-pinning-2
  #   networks:
  #     - titanh_network
  #   volumes:
  #     - ./config/pinning/node-2:/home/titanh-pinning/config
  #     - ./scripts/pinning/run-nodes.sh:/home/titanh-pinning/scripts/run-nodes.sh
  #   environment:
  #     - PINNING_INSTANCES=3
  #     - VALIDATOR_SEED=${SEED_SUBSTRATE_NODE_2}
  #     - CHAIN_RPC=ws://titanh-substrate-2:9944
  #     - FAILURE_RETRY=2
  #   tty: true
  #   depends_on:
  #     - titanh-substrate-2
  #     - titanh-ipfs-2
  #   entrypoint: ["/home/titanh-pinning/scripts/run-nodes.sh"]