[package]
name = "ipfs-cli-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
sp-core = { version = "34.0.0" }
pem = "3.0.4"
hex = "0.4.3"
